# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"printnl": "00_core.ipynb",
         "printdict": "00_core.ipynb",
         "test_eqs": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://mccallion.github.io/rory/"

git_url = "https://github.com/mccallion/rory/tree/master/"

def custom_doc_links(name): return None
