# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"pnl": "helpers.ipynb",
         "printdict": "helpers.ipynb",
         "test_eqs": "helpers.ipynb",
         "flatten": "helpers.ipynb"}

modules = ["helpers.py"]

doc_url = "https://mccallion.github.io/rory/"

git_url = "https://github.com/mccallion/rory/tree/master/"

def custom_doc_links(name): return None
