# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['printnl', 'printdict']

# Cell
def printnl(*x,nl=2):
    """ Print x separated by nl=2 newlines."""
    print(*x,sep='\n'*nl)

# Cell
def printdict(d,n=2):
    """Print n=2 lines from a dict."""
    print(dict(list(d.items())[:n]))